### ISSUE TITLE
HTML text resources are partially skipped

### ISSUE THREAD

**Issue by TWiStErRob** [cashapp/paparazzi#316]
Version: 0.8.0

|Android Studio preview|emulator|paparazziRecord|
|-|-|-|
|<img src=https://user-images.githubusercontent.com/2906988/141012341-d409de74-e364-405b-a953-db955ed336a6.png />|<img  src=https://user-images.githubusercontent.com/2906988/141012383-29fc68c7-e7d3-478f-a37f-003042500de7.png />|<img  src=https://user-images.githubusercontent.com/2906988/141014224-b8238c83-886d-4896-8fab-1003fce532dc.png />

Problem of note: on `paparazziRecord` snapshot the text is not bold and the rest of the text is missing.
```xml
<string name="warning_no_location"><b>The widget needs to know where you are</b>. Please adjust your Location Settings by tapping here, then wait a moment.</string>
```

**Comment by TWiStErRob** [comment]
For reference https://github.com/TWiStErRob/net.twisterrob.sun/commit/bcbd0a53129742904ea74294fb55a871db01f4e0 will give us this state. Execute
```shell
gradlew :feature:configuration:recordPaparazziDebug -Pnet.twisterrob.build.screenshot-tests=true
```

**Comment by jrodbx** [comment]
I installed the last few stable versions of Android Studio and found out that html styles in string resources were not supported until Android Studio 4.1.

4.0.2 (left) vs 4.1 (right)
<img height="400" alt="Screen Shot 2021-11-21 at 9 03 04 PM" src="https://user-images.githubusercontent.com/1868149/142964546-38dce62d-5ca3-4bdd-9264-c05ae5a5578f.png"><img height="400" title="4.1 (release on October 12, 2020)" alt="Screen Shot 2021-11-21 at 9 04 56 PM" src="https://user-images.githubusercontent.com/1868149/142964560-b849e7ae-1cbb-4de5-a144-71397c2eee24.png">

Here are the relevant commits to the [studio-4.1 tagline](https://android.googlesource.com/platform/frameworks/layoutlib/+log/studio-4.1.0): 

- https://android.googlesource.com/platform/frameworks/layoutlib/+/eab564d763c4d33c8e09f5d3837f19845355b063%5E%21/#F0
- https://android.googlesource.com/platform/frameworks/layoutlib/+/27506a56be0fd61dff28da50633b13f8cd630693%5E%21/#F0
- https://android.googlesource.com/platform/frameworks/layoutlib/+/dc9e3746f8950c671f97a0561cfd632b3dbeed63%5E%21/#F0

Unfortunately, while Android Studio/LayoutLib 4.1 renders correctly, as of Paparazzi 0.9.0, this is still broken.  Why?

Looks like it has something to do with how the XML parser is reading the strings.

<img height="400" alt="Screen Shot 2021-11-23 at 12 12 00 PM" src="https://user-images.githubusercontent.com/1868149/143071707-b10939ea-f7a4-4871-9ecc-81982a0dcef7.png">

<img height="400" alt="Screen Shot 2021-11-23 at 12 11 42 PM" src="https://user-images.githubusercontent.com/1868149/143071734-27b47a52-6e31-4479-852f-5cb9b84a49cc.png">

**Comment by jrodbx** [comment]
Repro branch: https://github.com/cashapp/paparazzi/compare/jrod/2021-11-22/test-html-string-issue?expand=1

**Comment by TWiStErRob** [comment]
Wonder if slapping a CDATA around it would "fix" this, or show the `<b>` literally.

**Comment by jrodbx** [comment]
Partially fixed in https://issuetracker.google.com/issues/266681481 and https://issuetracker.google.com/issues/262773698.

Still remaining on https://issuetracker.google.com/issues/288441176.

**Comment by jrodbx** [comment]
This was fixed in the bump to Hedgehog.

See:
- https://issuetracker.google.com/issues/288441176
- https://github.com/cashapp/paparazzi/pull/1227

**Comment by TWiStErRob** [comment]
@jrodbx your last comment on https://issuetracker.google.com/issues/288441176 was that this is not fixed, did things change since then?
