### ISSUE TITLE
Compose AlertDialog with usePlatformDefaultWidth = false is rendered cropped

### ISSUE THREAD

**Issue by marosseleng** [cashapp/paparazzi#680]
**Description**
Rendering a `@Composable` containing `AlertDialog` with `DialogProperties.usePlatformDefaultWidth = false` results in dialog to be cropped if it is wider than the platform default width. I found that property to be a culprit, while adding screenshot tests for my library ([draft PR](https://github.com/marosseleng/compose-material3-datetime-pickers/pull/56)).
Screenshots of `TimePickerDialog` look fine, however in `DatePickerDialog` screenshots, the dialog's width is always cropped. The only difference in dialog's configuration is `DialogProperties.usePlatformDefaultWidth = false` for the date picker.

**Steps to Reproduce**
Use the following composable:
```kotlin
    MaterialTheme {
        AlertDialog(
            onDismissRequest = {},
            text = {
                Row {
                    Box(modifier = Modifier
                        .size(width = 40.dp, height = 80.dp)
                        .background(Color.Green))
                    Box(modifier = Modifier
                        .size(width = 40.dp, height = 80.dp)
                        .background(Color.Red))
                    Box(modifier = Modifier
                        .size(width = 40.dp, height = 80.dp)
                        .background(Color.Black))
                    Box(modifier = Modifier
                        .size(width = 40.dp, height = 80.dp)
                        .background(Color.Blue))
                    Box(modifier = Modifier
                        .size(width = 40.dp, height = 80.dp)
                        .background(Color.Cyan))
                    Box(modifier = Modifier
                        .size(width = 40.dp, height = 80.dp)
                        .background(Color.Gray))
                    Box(modifier = Modifier
                        .size(width = 40.dp, height = 80.dp)
                        .background(Color.Magenta))
                }
            },
            confirmButton = {},
            properties = DialogProperties(usePlatformDefaultWidth = false)
        )
    }
```
with Paparazzi config:
```kotlin
    // Paparazzi config
    @get: Rule
    public val rule: Paparazzi = Paparazzi(
        deviceConfig = DeviceConfig.PIXEL_6_PRO.copy(
            softButtons = false,
        ),
        maxPercentDifference = 0.0,
        showSystemUi = false,
    )
```
Snapshot of the above called in `paparazzi.snapshot {}` (dialog's width is cropped) - First screenshot

When we change `usePlatformDefaultWidth` to `true`, the `paparazzi.snapshot{}` crops the content instead (consistent with the "real" behavior of `usePlatformDefaultWidth = true`, which is default) - Second screenshot

**Expected behavior**
I would expect the dialog would stretch. Screenshot of running `@Preview @Composable` of the above - third screenshot

**Additional information:**
- Paparazzi Version: 1.2.0-SNAPSHOT
- OS: MacOS Ventura 13.0.1
- Compile SDK: 33
- Gradle Version: 7.6
- Android Gradle Plugin Version: 7.3.1
- Android Studio: Flamingo | 2022.2.1 Canary 11, Build #AI-222.4459.24.2221.9445173

**Screenshots**
Paparazzi-usePlatformDefaultWidth=false
![paparazzi-usePlatformDefaultWidth=false](https://user-images.githubusercontent.com/9325961/212136907-1eccda1a-5c54-4fbf-9095-878b885b6b80.png)
Paparazzi-usePlatformDefaultWidth=true
![paparazzi-usePlatformDefaultWidth=true](https://user-images.githubusercontent.com/9325961/212137328-96ebd9e3-2de6-44fa-84c2-fcb68408483b.png)
Emulator preview (Pixel 6 Pro)
![AS-preview-pixel6pro](https://user-images.githubusercontent.com/9325961/212137733-8ff220fa-a1e4-48b8-b826-25446e6016c3.png)

Thanks for any inpu!

**Comment by dniHze** [comment]
Can you verify that AS preview is generated properly for this compostable? It might be not supported properly by layoutlib.

**Comment by marosseleng** [comment]
Sure, at least on Flamingo it seems to behave correctly. But I'm not sure whether preview in AS knows about the desired device's size. 
![image](https://user-images.githubusercontent.com/9325961/212462841-f67a63f7-0225-4a75-b0d0-f818fc9ad391.png)

**Comment by jrodbx** [comment]
Can you try/confirm on Electric Eel?  That's the version of layoutlib backing version 1.2.0.

**Comment by marosseleng** [comment]
@jrodbx It, indeed, seems that the problem is with layoutlib, as the same problem happens on Electric Eel (2022.1.1 #AI-221.6008.13.2211.9477386).

![Screenshot from 2023-01-20 08-23-53](https://user-images.githubusercontent.com/9325961/213641624-44a65296-945a-48c3-bbe8-0b3d879e18fa.png)

**Comment by dniHze** [comment]
@marosseleng it might be worth filling a bug report for Android Studio layout preview on [IssueTracker](https://issuetracker.google.com/issues/new?component=192708&template=840533).

**Comment by jrodbx** [comment]
Confirmed as fixed in Flamingo

**Comment by alashow** [comment]
@jrodbx It was either never fixed or it's a regression: I can still observe this issue on Paparazzi 1.3.1 and also in Android Studio Giraffe (2023.3.1, #AI-223.8836.35.2231.10406996)

**Comment by efemoney** [comment]
Still an issue with latest Paparazzi 1.3.4 (Iguana layout lib). 

I'm using Jellybug (canary) and I am seeing that normal preview does NOT have this problematic behavior. Maybe its actually fixed now.

**Comment by TWiStErRob** [comment]
@efemoney Jellyfish/Ladybug?

**Comment by efemoney** [comment]
Haha, Ladybug. Sorry, slow day 😅

**Comment by geoff-powell** [comment]
Update here, this issue is unfortunately still present with AS Koala (LayoutLib 14.0.11) and AS Ladybug (LayoutLib 15.0.4)

Ladybug Feature Drop [Left]
Ladybug Patch 1 [Right]
![Image](https://github.com/user-attachments/assets/1197a91a-cbaf-4866-bf93-a70a29d39a20)
